# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('in_date', models.DateTimeField(default=datetime.datetime(2016, 9, 29, 11, 8, 22, 799036), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430')),
                ('out_date', models.DateTimeField(default=datetime.datetime(2016, 9, 29, 11, 8, 22, 799082), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0438')),
                ('pid', models.CharField(max_length=40, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('photo', models.CharField(max_length=250, verbose_name='\u0424\u043e\u0442\u043e')),
                ('description', models.CharField(max_length=255, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440',
            },
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u0412\u0438\u0434 \u0442\u043e\u0432\u0430\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0412\u0438\u0434 \u0442\u043e\u0432\u0430\u0440\u0430',
                'verbose_name_plural': '\u0412\u0438\u0434 \u0442\u043e\u0432\u0430\u0440\u0430',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product_type', verbose_name='\u0412\u0438\u0434 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
