# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20160929_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 29, 12, 16, 59, 371075), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='ART', max_length=40, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
    ]
