# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160929_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 29, 12, 40, 56, 605702), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
    ]
