# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20161004_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_log',
            old_name='price_in',
            new_name='money_in',
        ),
        migrations.RenameField(
            model_name='sale_log',
            old_name='price_out',
            new_name='money_out',
        ),
        migrations.AlterField(
            model_name='product',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 12, 40, 1, 708279), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='sale_log',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 12, 40, 1, 707376)),
        ),
    ]
