# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20161004_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_log',
            old_name='product_pid',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 14, 30, 39, 748637), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='sale_log',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 14, 30, 39, 747688)),
        ),
    ]
