# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20170404_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='discont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430')),
                ('procent', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0438\u0434\u043a\u0438',
                'verbose_name_plural': '\u0421\u043a\u0438\u0434\u043a\u0438',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 17, 55, 13, 86112), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='out_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 17, 55, 13, 86149), editable=False, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0438'),
        ),
        migrations.AlterField(
            model_name='sale_log',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 17, 55, 13, 85332)),
        ),
    ]
