# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20170404_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 18, 35, 47, 238592), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='out_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 4, 18, 35, 47, 238633), editable=False, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0438'),
        ),
        migrations.AlterField(
            model_name='sale_log',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 18, 35, 47, 237741)),
        ),
    ]
