# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20170405_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 16, 29, 11, 98453), verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0432\u043e\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='out_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 5, 16, 29, 11, 98489), editable=False, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0438'),
        ),
        migrations.AlterField(
            model_name='sale_log',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 16, 29, 11, 97665)),
        ),
    ]
