# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20170911_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
