# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20170911_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale_log',
            options={'permissions': (('view_all', '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0432\u0441\u0435\u0445 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439'),)},
        ),
    ]
