# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20170914_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_log',
            name='discont',
            field=models.IntegerField(default=0),
        ),
    ]
